export type YealinkVariable = 
| 'mac'
| 'ip'
| 'model'
| 'firmware'
| 'active_url'
| 'active_user'
| 'active_host'
| 'local'
| 'remote'
| 'display_local'
| 'display_remote'
| 'call_id'
| 'callerID'
| 'calledNumber'
| 'exp_number'
| 'ehs_number'
| 'udisk_number'
| 'usbheadset_number'
| 'wifi_number'
| 'bluetooth_number'
| 'vpn_ip'
| 'cfg_all'
| 'cfg_local';

export default YealinkVariable;
